group: travis_latest

language: python

services:
  - docker

cache: pip

matrix:
  include:
    - python: "3.6"
      env: 
        - ONE_JOB_ONLY_TESTS=false
    - python: "3.7"
      env: 
        - ONE_JOB_ONLY_TESTS=false
    - python: "3.8"
      env: 
        - ONE_JOB_ONLY_TESTS=true
        - BUILD_DOCKER_IMAGES=true

install: 
  - pip install tox-travis coveralls pyyaml
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: 
  - tox
  - ./buildDockerImages.sh


after_success:
  - coveralls


notifications:
  webhooks: https://coveralls.io/webhook
