group: travis_latest

language: python

services:
  - docker

cache: pip

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      env: 
       - BUILD_DOCKER_IMAGES=true

install: 
  - pip install tox-travis coveralls pyyaml
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: 
  - tox
  - ./buildDockerImages.sh


after_success:
  # Only upload coverage report from pythonn 3.8 test run if BUILD_DOCKER_IMAGES is not null and not empty
  - |
    if [ -n "${BUILD_DOCKER_IMAGES}" ]; then
      coveralls
    fi

notifications:
  webhooks: https://coveralls.io/webhook
